module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'hsl(var(--color-primary))',
        'primary-foreground': 'hsl(var(--color-primary-foreground))',
        'primary-light': 'hsl(var(--color-primary-light))',
        'primary-dark': 'hsl(var(--color-primary-dark))',
        background: 'hsl(var(--color-background))',
        foreground: 'hsl(var(--color-foreground))',
        card: 'hsl(var(--color-card))',
        'card-foreground': 'hsl(var(--color-card-foreground))',
        popover: 'hsl(var(--color-popover))',
        'popover-foreground': 'hsl(var(--color-popover-foreground))',
        secondary: 'hsl(var(--color-secondary))',
        'secondary-foreground': 'hsl(var(--color-secondary-foreground))',
        muted: 'hsl(var(--color-muted))',
        'muted-foreground': 'hsl(var(--color-muted-foreground))',
        accent: 'hsl(var(--color-accent))',
        'accent-foreground': 'hsl(var(--color-accent-foreground))',
        destructive: 'hsl(var(--color-destructive))',
        'destructive-foreground': 'hsl(var(--color-destructive-foreground))',
        border: 'hsl(var(--color-border))',
        input: 'hsl(var(--color-input))',
        ring: 'hsl(var(--color-ring))',
        'sidebar-background': 'hsl(var(--color-sidebar-background))',
        'sidebar-foreground': 'hsl(var(--color-sidebar-foreground))',
        'sidebar-primary': 'hsl(var(--color-sidebar-primary))',
        'sidebar-primary-foreground':
          'hsl(var(--color-sidebar-primary-foreground))',
        'sidebar-accent': 'hsl(var(--color-sidebar-accent))',
        'sidebar-accent-foreground':
          'hsl(var(--color-sidebar-accent-foreground))',
        'sidebar-border': 'hsl(var(--color-sidebar-border))',
        'sidebar-ring': 'hsl(var(--color-sidebar-ring))',
      },
      fontFamily: {
        heading: 'var(--font-family-heading)',
        body: 'var(--font-family-body)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  safelist: [
    'text-primary',
    'text-primary-foreground',
    'text-secondary',
    'text-secondary-foreground',
    'text-muted',
    'text-muted-foreground',
    'text-accent',
    'text-accent-foreground',
    'text-destructive',
    'text-destructive-foreground',
    'bg-primary',
    'bg-primary-foreground',
    'bg-secondary',
    'bg-secondary-foreground',
    'border-primary',
    'border-secondary',
    'hover:text-primary',
    'hover:bg-primary',
    'hover:border-primary',
    'group-hover:text-primary',
    'group-hover:bg-primary',
    'group-hover:border-primary',
  ],
}
